# Generated by Django 3.0.8 on 2020-09-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20, verbose_name='Post type'),
        ),
    ]
