# Generated by Django 3.0.8 on 2020-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200930_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, help_text='Leave it blank to make the post public', max_length=25, null=True, verbose_name='Password'),
        ),
    ]
